/**
 * Newspaper clippings library — image paths, dates, and descriptions.
 * Images live in assets/media/newspaper-clippings/
 */

/** @typedef {{ file: string, sort: string, dateLabel: string, description: string, headline?: string, link?: string }} Clipping */

/** @type {Clipping[]} */
export const CLIPPINGS = [
  {
    file: 'malay-mail-2004-murder-suspects-police-brutality-allegation-rajpal-singh.png',
    sort: '2004-01-01',
    dateLabel: '2004',
    description: 'Malay Mail newspaper clipping from 2004 titled Murder suspects claim police beat them up, featuring defense lawyer Rajpal Singh representing a suspect at the Selayang Magistrate\'s Court.',
  },
  {
    file: 'new-straits-times-murder-trial-selayang-court-2004-rajpal-singh.JPG',
    sort: '2004-02-25',
    dateLabel: '25 February 2004',
    description: 'New Straits Times newspaper clipping dated February 25, 2004, reporting on four men charged with murder at the Selayang Magistrate\'s Court, represented by defense lawyer Rajpal Singh.',
  },
  {
    file: 'selayang-magistrate-court-murder-case-2004-rajpal-singh.JPG',
    sort: '2004-02-25',
    dateLabel: '25 February 2004',
    description: 'Newspaper clipping from February 25, 2004, reporting on four men charged with murder at the Selayang Magistrate\'s Court, featuring defense lawyer Rajpal Singh and allegations of police brutality.',
  },
  {
    file: 'rajpal-singh-gk-ganesan-hindraf-court-case-sinar-harian-2007.png',
    sort: '2007-11-30',
    dateLabel: '30 November 2007',
    description: 'Newspaper clipping from Sinar Harian dated November 30, 2007, showing defense lawyers Rajpal Singh and G.K. Ganesan during the Selayang Sessions Court case involving Hindraf rally participants.',
  },
  {
    file: 'new-straits-times-murder-acquittal-2007-rajpal-singh.JPG',
    sort: '2007-09-01',
    dateLabel: '1 September 2007',
    description: 'New Straits Times newspaper clipping dated September 1, 2007, reporting on the acquittal of two men, P. Balasubramaniam and R. Rajesh Singam, in a high-profile murder case defended by Rajpal Singh.',
  },
  {
    file: 'batu-caves-illegal-assembly-court-case-2007-rajpal-singh.JPG',
    sort: '2007-06-01',
    dateLabel: '2007',
    description: 'Newspaper clipping from The Star reporting on the Batu Caves illegal assembly case at the Shah Alam Sessions Court, featuring the involvement of lawyer Rajpal Singh as a Bar Council volunteer.',
  },
  {
    file: 'the-star-newspaper-front-page-december-5-2007-hindraf-trial-rajpal-singh.png',
    sort: '2007-12-05',
    dateLabel: '5 December 2007',
    description: 'Front page cover of The Star newspaper from December 5, 2007, featuring the headline \'Court drama\' regarding the Hindraf trial and the involvement of lawyer Rajpal Singh.',
  },
  {
    file: 'rajpal-singh-uthayakumar-malay-mail-hindraf-rally-trial-2007.png',
    sort: '2007-12-05',
    dateLabel: '5 December 2007',
    description: 'Malay Mail newspaper clipping from December 5, 2007, titled Trio walk out of rally trial, detailing lawyer Rajpal Singh discharging himself from the Hindraf Batu Caves court case.',
  },
  {
    file: 'rajpal-singh-anwar-ibrahim-sodomy-trial-not-guilty-the-sun-newspaper-2008.png',
    sort: '2008-01-01',
    dateLabel: '2008',
    description: 'Newspaper clipping from theSun titled Anwar pleads not guilty, highlighting Bar Council observer Rajpal Singh and the defense team during the 2008 Sessions Court arraignment.',
  },
  {
    file: 'batu-caves-election-campaign-datuk-muniandy-mohan-rajpal-singh-2008.JPG',
    sort: '2008-03-01',
    dateLabel: 'c. 2008',
    description: 'Tamil newspaper clipping from the c. 2008 Malaysian general election campaign in the Batu Caves constituency, showing Barisan Nasional candidate T. Mohan, Datuk Muniandy, and lawyer Rajpal Singh.',
  },
  {
    file: 'rajpal-singh-lim-yee-lan-anbuchelvan-sangker-alagendran-drug-acquittal-2009.png',
    sort: '2009-01-01',
    dateLabel: '2009',
    description: 'Malaysian Tamil newspaper clipping titled Ganja Case: Anbuselvan, Shankar, Alagendran Acquitted, showing defense lawyer Rajpal Singh walking outside court with his clients.',
  },
  {
    file: 'the-star-newspaper-drug-trafficking-acquittal-weight-discrepancy-rajpal-singh-2009.JPG',
    sort: '2009-07-24',
    dateLabel: '24 July 2009',
    description: 'Newspaper clipping from The Star dated July 24, 2009, reporting on the acquittal of three individuals in a drug trafficking case due to weight discrepancies, involving defense lawyer Rajpal Singh.',
  },
  {
    file: 'teoh-beng-hock-inquest-rajpal-singh-sin-chew-daily-2009.png',
    sort: '2009-08-11',
    dateLabel: '11 August 2009',
    description: 'Sin Chew Daily newspaper clipping from August 11, 2009, regarding the Teoh Beng Hock inquest, featuring legal counsel Rajpal Singh and forensic teams at Plaza Masalam.',
  },
  {
    file: 'teoh-beng-hock-inquest-rajpal-singh-nanyang-siang-pau-2009.png',
    sort: '2009-08-11',
    dateLabel: '11 August 2009',
    description: 'Nanyang Siang Pau newspaper clipping from August 11, 2009, covering the Teoh Beng Hock inquest and forensic site investigations involving legal counsel Rajpal Singh.',
  },
  {
    file: 'teoh-beng-hock-inquest-forensic-report-august-2009-rajpal-singh.JPG',
    sort: '2009-08-11',
    dateLabel: '11 August 2009',
    description: 'Chinese newspaper clipping from August 11, 2009, covering the Teoh Beng Hock inquest and forensic investigations into mysterious stains, with legal representation including Rajpal Singh.',
  },
  {
    file: 'teoh-beng-hock-inquest-dna-findings-august-2009-rajpal-singh.JPG',
    sort: '2009-08-01',
    dateLabel: 'August 2009',
    description: 'Newspaper clipping from August 2009 regarding the Teoh Beng Hock inquest, reporting on unidentified male DNA findings and the involvement of legal counsel including Rajpal Singh.',
    link: 'https://www.malaysianbar.org.my/cms/upload_files/document/Teoh%20Beng%20Hock%20Verdict.pdf',
  },
  {
    file: 'selvam-murder-case-court-trial-2009-rajpal-singh.JPG',
    sort: '2009-06-01',
    dateLabel: '2009',
    description: 'Tamil newspaper clipping reporting on a 2009 murder trial in Malaysia, featuring defense lawyers Rajpal Singh and N. Sivananthan questioning the police investigation process.',
  },
  {
    file: 'new-sunday-times-penal-code-review-december-2009-rajpal-singh.JPG',
    sort: '2009-12-06',
    dateLabel: '6 December 2009',
    description: 'New Sunday Times newspaper clipping dated December 6, 2009, featuring an article titled \'Review code, urge criminal lawyers\' with comments from criminal law expert Rajpal Singh and Edmund Bon on Penal Code reforms.',
  },
  {
    file: 'malaysian-penal-code-reform-advocacy-2009-rajpal-singh.JPG',
    sort: '2009-12-06',
    dateLabel: '6 December 2009',
    description: 'New Sunday Times newspaper clipping from December 6, 2009, featuring criminal law expert Rajpal Singh and Edmund Bon calling for a review of Malaysia\'s outdated Penal Code.',
  },
  {
    file: 'rajpal-singh-new-straits-times-2010-court-assigned-lawyers-capital-punishment.JPG',
    sort: '2010-07-01',
    dateLabel: 'July 2010',
    description: 'New Straits Times newspaper clipping from July 2010 titled 3-year rule for these lawyers, featuring comments from Bar Council Criminal Law Committee chairman Rajpal Singh on legal defense regulations.',
  },
  {
    file: 'rajpal-singh-selangor-bar-chairman-2010-official-documents.png',
    sort: '2010-07-01',
    dateLabel: 'July 2010',
    description: 'Rajpal Singh, Chairman of the Selangor Bar Committee, speaking about the importance of physical official documentation in an article from Mingguan MStar, July 2010.',
  },
  {
    file: 'rajpal-singh-selangor-bar-hockey-league-sinar-harian-2010.png',
    sort: '2010-11-10',
    dateLabel: '10 November 2010',
    description: 'Sinar Harian sports newspaper clipping from November 10, 2010, showing lawyer Rajpal Singh Mukhtiar Singh and the Selangor Bar hockey team celebrating their first Liga Hoki Selangor win.',
  },
  {
    file: 'rajpal-singh-m-seldas-edwinmaranda-kosmo-murder-trial-2011.png',
    sort: '2011-01-01',
    dateLabel: '2011',
    description: 'Kosmo newspaper clipping titled Dipenjara kerana bunuh jiran, detailing the defense mitigation by lawyer Rajpal Singh for M. Seldas following his reduced culpable homicide conviction.',
  },
  {
    file: 'new-straits-times-drug-trafficking-acquittal-2011-rajpal-singh.JPG',
    sort: '2011-05-27',
    dateLabel: '27 May 2011',
    description: 'New Straits Times newspaper clipping dated May 27, 2011, reporting on the acquittal of three individuals in a drug trafficking case, featuring defense lawyer Rajpal Singh.',
  },
  {
    file: 'rajpal-singh-ewe-peng-lip-rape-case-ruling-new-straits-times-2012.png',
    sort: '2012-09-01',
    dateLabel: 'September 2012',
    description: 'New Straits Times newspaper clipping from September 2012 titled Council Ruling in rape case fair, featuring comments from Bar Council Criminal Law Committee chairman Rajpal Singh.',
  },
  {
    file: 'chinese-press-murder-acquittal-selayang-court-2015-rajpal-singh.JPG',
    sort: '2015-01-01',
    dateLabel: '2015',
    description: 'Chinese newspaper clipping reporting on the acquittal of a man accused of murdering his girlfriend, featuring defense legal arguments by lawyer Rajpal Singh that raised reasonable doubt.',
  },
  {
    file: 'rajpal-singh-lawyer-muar-high-court-kidnapping-case-2016.png',
    sort: '2016-01-01',
    dateLabel: '2016',
    description: 'Malaysian criminal defense lawyer Rajpal Singh (Rajaban) and co-counsel outside the Muar High Court during a 2016 kidnapping trial sentencing, featured in a Chinese newspaper clipping.',
  },
  {
    file: 'rajpal-singh-lawyer-acquittal-court-case-2016.png',
    sort: '2016-01-01',
    dateLabel: '2016',
    description: 'Malaysian criminal defense lawyer Rajpal Singh shaking hands with acquitted client inside the Kuala Lumpur High Court after a verdict, featured in a Chinese newspaper clipping.',
  },
  {
    file: 'rajpal-singh-cheh-chun-nam-kosmo-murder-acquittal-2016.png',
    sort: '2016-01-01',
    dateLabel: '2016',
    description: 'Kosmo newspaper clipping titled Penjual nasi ayam bebas tuduhan bunuh teman wanita, showing chicken rice seller Cheh Chun Nam shaking hands with his defense lawyer Rajpal Singh after a High Court acquittal.',
  },
  {
    file: 'ng-yuk-tim-murder-trial-2016-poon-wai-hong-rajpal-singh.JPG',
    sort: '2016-01-01',
    dateLabel: '2016',
    description: 'Chinese newspaper clipping from 2016 reporting on the murder trial of Poon Wai Hong, known as the \'cosplay killer,\' for the death of Ng Yuk Tim, featuring defense counsel Dato\' Rajpal Singh.',
  },
  {
    file: 'rajpal-singh-court-acquittal-the-star-2016.png',
    sort: '2016-01-20',
    dateLabel: '20 January 2016',
    description: 'Newspaper clipping from The Star dated January 20, 2016, featuring an article about a murder acquittal involving lawyer Rajpal Singh and a secondary headline regarding a successful murder appeal.',
  },
  {
    file: 'the-star-murder-acquittal-cheras-2016-rajpal-singh.JPG',
    sort: '2016-01-20',
    dateLabel: '20 January 2016',
    description: 'The Star newspaper clipping from January 20, 2016, reporting on the acquittal of a man accused of killing his girlfriend, featuring defense lawyer Dato\' Rajpal Singh.',
  },
  {
    file: 'nicky-liow-court-case-charge-withdrawal-2018-rajpal-singh.JPG',
    sort: '2018-09-08',
    dateLabel: '8 September 2018',
    description: 'Prime News Chinese newspaper clipping from September 8, 2018, reporting on the withdrawal of charges against Datuk Nicky Liow Soon Hee, featuring defense lawyer Dato\' Rajpal Singh.',
  },
  {
    file: 'nicky-liow-court-charges-withdrawn-2018-rajpal-singh.JPG',
    sort: '2018-09-08',
    dateLabel: '8 September 2018',
    description: 'China Press (中国报) newspaper clipping from September 8, 2018, reporting on the withdrawal of charges against Datuk Nicky Liow Soon Hee, featuring defense lawyer Dato\' Rajpal Singh.',
  },
  {
    file: 'nicky-liow-rela-assault-charges-dropped-2018-rajpal-singh.JPG',
    sort: '2018-09-08',
    dateLabel: '8 September 2018',
    description: 'New Straits Times newspaper clipping from September 8, 2018, reporting on the withdrawal of two charges against Datuk Seri Nicky Liow Soon Hee in the RELA assault case, with defense lawyer Dato\' Rajpal Singh.',
  },
  {
    file: 'rela-assault-case-dnaa-2018-nicky-liow-rajpal-singh.JPG',
    sort: '2018-09-08',
    dateLabel: '8 September 2018',
    description: 'The Star newspaper clipping from September 8, 2018, reporting on a RELA member withdrawing a police report against businessman Datuk Seri Nicky Liow Soon Hee, with defense counsel Dato\' Rajpal Singh present.',
  },
  {
    file: 'RELA-assault-case-compensation-rejection-2018-rajpal-singh.JPG',
    sort: '2018-08-15',
    dateLabel: '15 August 2018',
    description: 'Newspaper clipping from August 15, 2018, reporting on RELA\'s refusal to accept compensation from businessman Nicky Liow in an assault case, featuring defense lawyer Dato\' Rajpal Singh.',
  },
  {
    file: 'rela-members-reject-compensation-nicky-liow-case-2018-rajpal-singh.JPG',
    sort: '2018-08-01',
    dateLabel: '2018',
    description: 'Harian Metro newspaper clipping from 2018 reporting on RELA members rejecting a compensation offer from Datuk Seri Nicky Liow Soon Hee, with legal defense by Dato\' Rajpal Singh.',
  },
  {
    file: 'nicky-liow-rela-assault-trial-2018-rajpal-singh.JPG',
    sort: '2018-09-01',
    dateLabel: 'September 2018',
    description: 'Chinese newspaper clipping from September 2018 reporting on the court proceedings for the RELA assault case involving Datuk Seri Nicky Liow Soon Hee and his lawyer Dato\' Rajpal Singh.',
  },
  {
    file: 'chinese-press-nicky-liow-rela-trial-update-rajpal-singh-2018.JPG',
    sort: '2018-09-01',
    dateLabel: '2018',
    description: 'Chinese newspaper clipping from 2018 reporting on court trial proceedings regarding the assault of RELA personnel by Datuk Seri Nicky Liow Soon Hee, with defense lawyer Dato\' Rajpal Singh.',
  },
  {
    file: 'rela-assault-case-report-withdrawal-2018-rajpal-singh.JPG',
    sort: '2018-11-01',
    dateLabel: 'November 2018',
    description: 'Newspaper clipping from November 2018 reporting on the withdrawal of police reports by RELA members in the assault case involving Datuk Seri Nicky Liow, featuring defense lawyer Dato\' Rajpal Singh.',
  },
  {
    file: 'nicky-liow-rela-assault-settlement-2019-rajpal-singh.JPG',
    sort: '2019-05-10',
    dateLabel: '10 May 2019',
    description: 'China Press (中国报) newspaper clipping from May 10, 2019, reporting on the settlement of the RELA assault case involving Datuk Nicky Liow Soon Hee and his lawyer Dato\' Rajpal Singh.',
  },
  {
    file: 'nicky-liow-rela-assault-acquittal-2019-rajpal-singh.JPG',
    sort: '2019-05-11',
    dateLabel: '11 May 2019',
    description: 'The Star newspaper clipping from May 11, 2019, reporting on the acquittal of Datuk Seri Nicky Liow Soon Hee in the RELA assault case, featuring defense lawyer Dato\' Rajpal Singh.',
  },
  {
    file: 'tamil-press-nicky-liow-rela-case-settlement-2019-rajpal-singh.JPG',
    sort: '2019-05-01',
    dateLabel: 'May 2019',
    description: 'Tamil language newspaper article from May 2019 covering the court acquittal of Datuk Seri Nicky Liow Soon Hee in the RELA assault case, featuring defense attorney Dato\' Rajpal Singh.',
  },
  {
    file: 'paul-yong-choo-kiong-exco-duty-status-2019-rajpal-singh.JPG',
    sort: '2019-11-01',
    dateLabel: 'November 2019',
    description: 'Malaysiakini news report from November 2019 regarding the status of Perak Exco Paul Yong Choo Kiong as he faced rape allegations and sought a case transfer to the High Court.',
  },
  {
    file: 'poon-wai-hong-cosplay-killer-appeal-2019-rajpal-singh.JPG',
    sort: '2019-09-12',
    dateLabel: '12 September 2019',
    description: 'Free Malaysia Today newspaper clipping from September 12, 2019, reporting on the Court of Appeal reducing the death sentence of Poon Wai Hong, the \'cosplay killer\', to 22 years\' jail, represented by lawyer Dato\' Rajpal Singh.',
  },
  {
    file: 'poon-wai-hong-culpable-homicide-appeal-ruling-2019-rajpal-singh.JPG',
    sort: '2019-09-01',
    dateLabel: 'September 2019',
    description: 'Chinese news report from September 2019 documenting the Court of Appeal\'s decision to commute the death sentence of Poon Wai Hong to 22 years\' imprisonment, with defense lawyer Dato\' Rajpal Singh leading the appeal.',
  },
  {
    file: 'poon-wai-hong-appeal-ruling-2019-rajpal-singh.JPG',
    sort: '2019-09-01',
    dateLabel: '2019',
    description: 'Chinese newspaper article from 2019 detailing the Court of Appeal\'s decision to reduce the sentence of Poon Wai Hong, known as the \'cosplay killer,\' represented by defense lawyer Dato\' Rajpal Singh.',
  },
  {
    file: 'paul-yong-rape-trial-date-setting-rajpal-singh-2020.JPG',
    sort: '2020-07-16',
    dateLabel: '16 July 2020',
    description: 'News report dated July 16, 2020, featuring defense lawyer Dato\' Rajpal Singh speaking to the media outside the Ipoh Sessions Court regarding the trial dates set for former Perak assemblyman Paul Yong.',
  },
  {
    file: 'nicky-gang-14-men-dnaa-shah-alam-2021-rajpal-singh.JPG',
    sort: '2021-01-01',
    dateLabel: '2021',
    description: 'Newspaper clipping from The Star reporting on 14 individuals linked to the Nicky Liow \'Nicky Gang\' being granted a discharge not amounting to an acquittal (DNAA) in 2021, defended by lawyer Dato\' Rajpal Singh.',
  },
  {
    file: 'paul-yong-rape-trial-defense-ruling-2021-rajpal-singh.JPG',
    sort: '2021-12-07',
    dateLabel: '7 December 2021',
    description: 'Malay Mail newspaper report from December 7, 2021, covering the High Court\'s order for former Tronoh assemblyman Paul Yong to enter his defense in a rape case, with defense counsel Dato\' Rajpal Singh present.',
  },
  {
    file: 'paul-yong-rape-trial-prima-facie-ruling-rajpal-singh-2021.JPG',
    sort: '2021-12-08',
    dateLabel: '8 December 2021',
    description: 'Front page of The Star newspaper from December 8, 2021, reporting on the High Court\'s ruling that the prosecution established a prima facie case against Paul Yong Choo Kiong in his rape trial, defended by Dato\' Rajpal Singh.',
  },
  {
    file: 'nicky-gang-acquittal-court-of-appeal-2022-rajpal-singh.JPG',
    sort: '2022-07-07',
    dateLabel: '7 July 2022',
    description: 'Kosmo newspaper clipping from July 7, 2022, reporting on the acquittal of 14 individuals linked to the \'Nicky Gang\' organised crime group, featuring defense counsel Dato\' Rajpal Singh.',
  },
  {
    file: 'china-press-kk-mart-court-appearance-2024-march.JPG',
    sort: '2024-03-27',
    dateLabel: '27 March 2024',
    description: 'Front page of China Press from March 27, 2024, reporting on the court appearance of KK Mart founder Datuk Seri Chai Kee Kan and his wife regarding the \'Allah\' socks controversy.',
  },
  {
    file: 'the-star-kk-mart-directors-claim-trial-2024.JPG',
    sort: '2024-03-27',
    dateLabel: '27 March 2024',
    description: 'Front page of The Star newspaper from March 27, 2024, reporting on KK Group founder Datuk Seri Dr Chai Kee Kan and his wife pleading not guilty to charges over the \'Allah\' socks controversy.',
  },
  {
    file: 'kk-mart-legal-controversy-and-security-incidents-2024-march.JPG',
    sort: '2024-03-27',
    dateLabel: '27 March 2024',
    description: 'News report from The Star newspaper dated March 27, 2024, summarizing the court charges against KK Super Mart management and coverage of a firebombing incident at a convenience store location.',
  },
  {
    file: 'sin-chew-daily-kk-mart-sock-controversy-acquittal-rajpal-singh.png',
    sort: '2024-07-16',
    dateLabel: '16 July 2024',
    description: 'Sin Chew Daily newspaper clipping dated July 16, 2024, reporting on the acquittal of five individuals in the KK Mart sock controversy, featuring defense lawyer Rajpal Singh.',
  },
  {
    file: 'china-press-kk-mart-founder-acquittal-2024-rajpal-singh.JPG',
    sort: '2024-07-16',
    dateLabel: '16 July 2024',
    description: 'Front page of China Press from July 16, 2024, reporting on the acquittal of KK Mart founder Datuk Seri Chai Kee Kan and his wife, with defense attorney Dato\' Rajpal Singh, following the \'Allah\' socks controversy.',
  },
  {
    file: 'new-straits-times-kk-mart-acquittal-2024-rajpal-singh-report.JPG',
    sort: '2024-07-16',
    dateLabel: '16 July 2024',
    description: 'New Straits Times report from July 16, 2024, detailing the acquittal of KK Mart\'s leadership, represented by defense lawyer Dato\' Rajpal Singh, in the \'Allah\' socks case.',
  },
  {
    file: 'kk-mart-founder-chai-kee-kan-acquittal-2024-rajpal-singh.JPG',
    sort: '2024-07-16',
    dateLabel: 'July 2024',
    description: 'Chinese language newspaper clipping from July 2024 reporting on the acquittal of KK Mart founder Datuk Seri Chai Kee Kan and his wife, with defense lawyer Dato\' Rajpal Singh and Datuk David Gurupatham, following the \'Allah\' socks controversy.',
  },
  {
    file: 'kk-mart-legal-victory-2024-analysis-rajpal-singh.JPG',
    sort: '2024-07-16',
    dateLabel: 'July 2024',
    description: 'Detailed press report from China Press on the 2024 court acquittal of KK Mart\'s management, highlighting the defense strategy led by Dato\' Rajpal Singh and his legal team.',
  },
  {
    file: 'kk-mart-founder-chai-kee-kan-124-days-acquittal-rajpal-singh.JPG',
    sort: '2024-07-16',
    dateLabel: 'July 2024',
    description: 'Tamil newspaper article featuring KK Mart founder Datuk Seri Chai Kee Kan and his defense lawyer Dato\' Rajpal Singh, discussing his relief after 124 difficult days during the \'Allah\' socks legal controversy.',
  },
  {
    file: 'kk-mart-founder-acquittal-statement-tamil-press-2024.JPG',
    sort: '2024-07-16',
    dateLabel: 'July 2024',
    description: 'Tamil newspaper report documenting the reaction of KK Mart founder Datuk Seri Chai Kee Kan following his acquittal in the 2024 \'Allah\' socks case.',
  },
  {
    file: 'kosmo-fake-lawyer-scam-alert-michael-chong-shafee-rajpal-singh-2025.JPG',
    sort: '2025-12-15',
    dateLabel: '15 December 2025',
    description: 'Kosmo newspaper report from December 15, 2025, warning about syndicates impersonating lawyers to defraud scam victims, featuring Datuk Seri Michael Chong, Tan Sri Muhammad Shafee Abdullah, and lawyer Dato\' Rajpal Singh.',
  },
  {
    file: '8tv-news-fake-lawyer-scam-alert-michael-chong-rajpal-singh-2025.JPG',
    sort: '2025-12-15',
    dateLabel: '15 December 2025',
    description: '8TV News report from December 15, 2025, featuring Datuk Seri Michael Chong and lawyer Dato\' Rajpal Singh warning the public against fake \'lawyers\' promising to recover money for scam victims.',
  },
  {
    file: 'berita-harian-fake-law-firm-scam-alert-michael-chong-shafee-rajpal-singh-2025.JPG',
    sort: '2025-12-15',
    dateLabel: '15 December 2025',
    description: 'Berita Harian report from December 15, 2025, detailing how scammers impersonate law firms to exploit scam victims, featuring Datuk Seri Michael Chong and lawyers including Tan Sri Muhammad Shafee Abdullah and Dato\' Rajpal Singh.',
  },
  {
    file: 'berita-harian-law-firm-scam-alert-michael-chong-rajpal-singh-2025.JPG',
    sort: '2025-12-16',
    dateLabel: '16 December 2025',
    description: 'Berita Harian report from December 16, 2025, featuring Datuk Seri Michael Chong and lawyers including Dato\' Rajpal Singh and Tan Sri Muhammad Shafee Abdullah, warning against online scams impersonating law firms.',
  },
  {
    file: 'new-straits-times-legal-scam-alert-michael-chong-shafee-rajpal-singh-2025.JPG',
    sort: '2025-12-16',
    dateLabel: '16 December 2025',
    description: 'New Straits Times report from December 16, 2025, detailing how scammers exploit victims by posing as legal firms, featuring Datuk Seri Michael Chong, Tan Sri Muhammad Shafee Abdullah, and lawyer Dato\' Rajpal Singh.',
  },
  {
    file: 'the-star-fake-law-firm-scam-alert-2025-michael-chong-shafee-rajpal-singh.JPG',
    sort: '2025-12-17',
    dateLabel: '17 December 2025',
    description: 'The Star newspaper report from December 17, 2025, detailing how fake law firms exploit scam victims, featuring insights from Datuk Seri Michael Chong, Tan Sri Muhammad Shafee Abdullah, and lawyer Dato\' Rajpal Singh.',
  },
  {
    file: 'mothership-fake-law-firm-scam-alert-2025-michael-chong-shafee-rajpal-singh.JPG',
    sort: '2025-12-17',
    dateLabel: '17 December 2025',
    description: 'Mothership news report from December 17, 2025, detailing how scam victims in Malaysia are exploited a second time by fake law firms, featuring insights from Datuk Seri Michael Chong, Tan Sri Muhammad Shafee Abdullah, and lawyer Dato\' Rajpal Singh.',
  },
  {
    file: 'rajpal-singh-ka-ramu-shah-alam-high-court-murder-case.png',
    sort: '2000-01-01',
    dateLabel: 'Archive',
    description: 'Malaysian criminal defense lawyers Rajpal Singh and K.A. Ramu pictured in a Tamil newspaper clipping during a murder trial at the Shah Alam High Court.',
  },
  {
    file: 'rajpal-singh-harian-metro-junaidi-ibrahim-drug-trafficking-acquittal.png',
    sort: '2000-01-02',
    dateLabel: 'Archive',
    description: 'Harian Metro newspaper clipping titled Bebas hukuman gantung, showing defense lawyer Rajpal Singh with Junaidi Ibrahim after his drug trafficking acquittal.',
  },
  {
    file: 'rajpal-singh-dhanasekaran-drug-trafficking-acquittal-malaysia-tamil-news.png',
    sort: '2000-01-03',
    dateLabel: 'Archive',
    description: 'Tamil newspaper clipping titled Escaped from the hanging rope, showing defense lawyer Rajpal Singh outside the court with Dhanasekaran following his high-profile drug trafficking acquittal.',
  },
  {
    file: 'paul-yong-rape-trial-court-testimony-analysis-rajpal-singh.JPG',
    sort: '2020-06-01',
    dateLabel: 'Paul Yong trial',
    description: 'Newspaper report detailing court testimony in the rape trial of former Tronoh assemblyman Paul Yong, featuring cross-examination by defense counsel Dato\' Rajpal Singh regarding forensic evidence.',
  },
];
