/**
 * press-data-ms.js — Auto-generated Bahasa Malaysia locale. Run: node scripts/generate-ms-locale.mjs
 */

/** @type {{ id: string, label: string }[]} */
export const PRESS_CATEGORIES_MS = [
  {
    "id": "all",
    "label": "Semua"
  },
  {
    "id": "criminal-trials",
    "label": "Perbicaraan jenayah"
  },
  {
    "id": "civil-litigation",
    "label": "Litigasi sivil"
  },
  {
    "id": "kk-mart",
    "label": "KK Mart"
  },
  {
    "id": "bar-profession",
    "label": "Majlis peguam & profesion"
  },
  {
    "id": "video-social",
    "label": "Video & media sosial"
  },
  {
    "id": "community",
    "label": "Komuniti"
  }
];

/** @type {import('./press-data.js').PressItem[]} */
export const PRESS_ITEMS_MS = [
  {
    "id": "edge-sultanah-defamation-leave-2024",
    "url": "https://theedgemalaysia.com/node/726155",
    "title": "Editor Sarawak Report dinafikan kebenaran merayu sabitan fitnah",
    "excerpt": "Mahkamah Persekutuan menolak permohonan kebenaran merayu Clare Rewcastle-Brown dalam saman fitnah Sultanah Nur Zahirah; Vishnu Kumar mewakili Sultanah.",
    "publisher": "The Edge Malaysia",
    "sort": "2024-09-10",
    "dateLabel": "10 September 2024",
    "category": "civil-litigation",
    "type": "article",
    "featured": true,
    "counsel": "vishnu-kumar",
    "thumb": "assets/media/press/edge-sultanah-defamation-leave-2024.jpg"
  },
  {
    "id": "dailyexpress-sultanah-defamation-2024",
    "url": "https://www.dailyexpress.com.my/news/241653/apex-court-affirms-rewcastle-brown-two-others-defamed-sultanah/",
    "title": "Mahkamah Persekutuan sahkan Rewcastle Brown dan dua lagi memfitnah Sultanah",
    "excerpt": "Daily Express melaporkan Mahkamah Persekutuan mengekalkan liabiliti fitnah terhadap Clare Rewcastle-Brown; peguam Vishnu Kumar bagi Sultanah Nur Zahirah.",
    "publisher": "Daily Express",
    "sort": "2024-09-10",
    "dateLabel": "10 September 2024",
    "category": "civil-litigation",
    "type": "article",
    "counsel": "vishnu-kumar",
    "thumb": "assets/media/press/clare-rewcastle-brown-and-sultanah-nur-zahirah.jpg"
  },
  {
    "id": "edge-sultanah-defamation-appeal-2023",
    "url": "https://theedgemalaysia.com/node/683569",
    "title": "Perkataan dalam pernyataan dicadang ditafsir secara kasual, hujah peguam Sultanah",
    "excerpt": "Pendengaran Mahkamah Rayuan saman fitnah Clare Rewcastle-Brown oleh Sultanah Nur Zahirah; Vishnu Kumar berhujah Hakim Mahkamah Tinggi terlalu rumit mentafsir pernyataan dikatakan fitnah.",
    "publisher": "The Edge Malaysia",
    "sort": "2023-09-22",
    "dateLabel": "22 September 2023",
    "category": "civil-litigation",
    "type": "article",
    "counsel": "vishnu-kumar",
    "thumb": "assets/media/press/edge-sultanah-defamation-appeal-2023.jpg"
  },
  {
    "id": "nst-election-manifesto-2022",
    "url": "https://www.nst.com.my/opinion/columnists/2022/11/847350/polls-will-only-have-value-if-election-manifesto-legally-binding",
    "title": "Undi hanya bermakna jika manifesto pilihan raya mengikat undang-undang",
    "excerpt": "Ruangan pendapat merujuk hujahan Vishnu Kumar di Mahkamah Rayuan bahawa manifesto pilihan raya tidak boleh dikuatkuasakan secara guaman di Malaysia.",
    "publisher": "New Straits Times",
    "sort": "2022-11-05",
    "dateLabel": "5 November 2022",
    "category": "bar-profession",
    "type": "article",
    "counsel": "vishnu-kumar",
    "thumb": "assets/media/press/nst-election-manifesto-2022.jpg"
  },
  {
    "id": "malaymail-jonathan-wong-cheating-2024",
    "url": "https://www.malaymail.com/news/malaysia/2024/01/04/consultant-charged-with-cheating-man-of-rm33m-in-kl/110631",
    "title": "Perunding didakwa tipu lelaki RM3.3 juta di KL",
    "excerpt": "Pertuduhan Mahkamah Sesyen ke atas lesen pelaburan kripto; peguam Siti Anis Che Ab Wahab mewakili tertuduh berkaitan jamin.",
    "publisher": "Malay Mail",
    "sort": "2024-01-04",
    "dateLabel": "4 Januari 2024",
    "category": "criminal-trials",
    "type": "article",
    "featured": true,
    "counsel": "siti-anis",
    "thumb": "assets/media/press/malaymail-jonathan-wong-cheating-2024.jpg"
  },
  {
    "id": "bernama-jonathan-wong-cheating-2024",
    "url": "https://bernama.com/bm/news.php?id=2259453",
    "title": "Perunding syarikat didakwa tipu urusan lesen pelaburan RM3.3 juta",
    "excerpt": "Bernama melaporkan pertuduhan penipuan di Mahkamah Sesyen Kuala Lumpur; peguam Siti Anis Che Ab Wahab memohon jamin RM50,000.",
    "publisher": "Bernama",
    "sort": "2024-01-04",
    "dateLabel": "4 Januari 2024",
    "category": "criminal-trials",
    "type": "article",
    "counsel": "siti-anis",
    "thumb": "assets/media/press/bernama-jonathan-wong-cheating-2024.jpg"
  },
  {
    "id": "facebook-fmt-jonathan-wong-2024",
    "url": "https://www.facebook.com/share/197HPodYDY/?mibextid=wwXIfr",
    "title": "Ahli perniagaan mengaku tak salah pecah amanah RM4.3 juta",
    "excerpt": "Catatan media sosial Free Malaysia Today tentang Johnathan Wong Futt Po; peguam Siti Anis Che Ab Wahab hadir di Mahkamah Sesyen.",
    "publisher": "Free Malaysia Today (Facebook)",
    "sort": "2024-01-22",
    "dateLabel": "22 Januari 2024",
    "category": "criminal-trials",
    "type": "social",
    "counsel": "siti-anis",
    "thumb": "assets/media/press/fallback-facebook.svg"
  },
  {
    "id": "astro-minyak-masak-2023",
    "url": "https://www.astroawani.com/berita-malaysia/pemilik-pasar-raya-mini-didakwa-simpan-250kg-minyak-masak-121807",
    "title": "Pemilik pasar raya mini didakwa simpan 250kg minyak masak",
    "excerpt": "Astro Awani melaporkan pertuduhan pasar mini Batu Caves; Siti Anis Che Ab Wahab memohon pengurangan jamin tertuduh.",
    "publisher": "Astro Awani",
    "sort": "2023-12-15",
    "dateLabel": "15 Disember 2023",
    "category": "criminal-trials",
    "type": "article",
    "counsel": "siti-anis",
    "thumb": "assets/media/press/astro-minyak-masak-2023.jpg"
  },
  {
    "id": "hmetro-grab-murder-death-2023",
    "url": "https://www.hmetro.com.my/utama/2023/07/992766/bunuh-pemandu-grab-dua-warga-asing-dihukum-gantung",
    "title": "Bunuh pemandu Grab, dua warga asing dihukum gantung",
    "excerpt": "Sabitan bunuh di Mahkamah Tinggi Shah Alam ke atas pemandu e-hailing Aiman Nosri; peguam pembelaan Siti Anis Che Ab Wahab mohon penjara dan sebat.",
    "publisher": "Harian Metro",
    "sort": "2023-07-28",
    "dateLabel": "28 Julai 2023",
    "category": "criminal-trials",
    "type": "article",
    "counsel": "siti-anis",
    "thumb": "assets/media/press/hmetro-grab-murder-death-2023.jpg"
  },
  {
    "id": "hmetro-rewcastle-terengganu-2023",
    "url": "https://www.hmetro.com.my/mutakhir/2023/06/979881/bicara-kes-saman-clare-rewcastle-brown-kekal-di-mahkamah-kuala-terengganu",
    "title": "Bicara kes saman Clare Rewcastle-Brown kekal di Mahkamah Kuala Terengganu",
    "excerpt": "Harian Metro melaporkan permohonan pindah ditolak; Siti Anis Che Ab Wahab memegang watching brief bagi Sultanah Nur Zahirah.",
    "publisher": "Harian Metro",
    "sort": "2023-06-21",
    "dateLabel": "21 Jun 2023",
    "category": "criminal-trials",
    "type": "article",
    "counsel": "siti-anis",
    "thumb": "assets/media/press/hmetro-rewcastle-terengganu-2023.jpg"
  },
  {
    "id": "star-organised-crime-2026",
    "url": "https://www.thestar.com.my/news/nation/2026/05/25/11-men-charged-with-being-members-of-organised-crime-group",
    "title": "11 lelaki didakwa sebagai ahli kumpulan jenayah terancang",
    "excerpt": "Liputan pertuduhan jenayah terancang memaparkan peguam pembelaan jenayah Dato' Rajpal Singh di Malaysia.",
    "publisher": "The Star",
    "sort": "2026-05-25",
    "dateLabel": "25 Mei 2026",
    "category": "criminal-trials",
    "type": "article",
    "thumb": "assets/media/press/star-organised-crime-2026.jpg"
  },
  {
    "id": "malaysia-gazette-harmoni-2025",
    "url": "https://malaysiagazette.com/2025/04/12/hidup-harmoni-perpaduan-penting-rajpal/",
    "title": "Hidup harmoni, perpaduan penting — Dato' Rajpal Singh",
    "excerpt": "Dato' Rajpal Singh berkongsi pandangan mengenai keharmonian dan perpaduan dalam kehidupan masyarakat Malaysia.",
    "publisher": "Malaysia Gazette",
    "sort": "2025-04-12",
    "dateLabel": "12 April 2025",
    "category": "community",
    "type": "article",
    "featured": true,
    "thumb": "assets/media/press/malaysia-gazette-harmoni-2025.jpg"
  },
  {
    "id": "star-paul-yong-appeal-2024",
    "url": "https://www.thestar.com.my/news/nation/2024/09/05/apex-court-to-hear-paul-yong039s-rape-conviction-appeal-on-oct-23",
    "title": "Mahkamah Persekutuan akan dengar rayuan sabitan rogol Paul Yong",
    "excerpt": "Liputan rayuan Mahkamah Persekutuan melibatkan bekas ahli dewan Perak Paul Yong dan peguam Dato' Rajpal Singh.",
    "publisher": "The Star",
    "sort": "2024-09-05",
    "dateLabel": "5 September 2024",
    "category": "criminal-trials",
    "type": "article",
    "featured": true,
    "thumb": "assets/media/press/star-paul-yong-appeal-2024.jpg"
  },
  {
    "id": "bh-kk-mart-family-2024",
    "url": "https://www.bharian.com.my/berita/nasional/2024/07/1271686/124-hari-penuh-sengsara-dalam-hidup-saya-keluarga-pengasas-kk-mart",
    "title": "124 hari penuh sengsara — Pengasas KK Mart",
    "excerpt": "Laporan Berita Harian tentang keluarga pengasas KK Mart berikutan kontroversi stokin Allah, dengan Dato' Rajpal Singh sebagai peguam.",
    "publisher": "Berita Harian",
    "sort": "2024-07-15",
    "dateLabel": "15 Julai 2024",
    "category": "kk-mart",
    "type": "article",
    "thumb": "assets/media/press/bh-kk-mart.jpg"
  },
  {
    "id": "utusan-kk-mart-verdict-2024",
    "url": "https://www.utusan.com.my/nasional/2024/07/keputusan-mahkamah-diharap-tamatkan-isu-kk-mart/",
    "title": "Keputusan mahkamah diharap tamatkan isu KK Mart",
    "excerpt": "Dato' Rajpal Singh berkata mahkamah telah membuat keputusan dan orang awam tidak seharusnya melanjutkan isu KK Mart.",
    "publisher": "Utusan Malaysia",
    "sort": "2024-07-15",
    "dateLabel": "15 Julai 2024",
    "category": "kk-mart",
    "type": "article",
    "thumb": "assets/media/press/utusan-kk-mart.jpg"
  },
  {
    "id": "harapan-daily-kk-mart-2024",
    "url": "https://harapandaily.com/2024/03/27/justice-will-prevail-for-kk-mart/",
    "title": "Keadilan akan berpihak kepada KK Mart",
    "excerpt": "Laporan media tentang kes stokin Allah KK Mart memaparkan peguam pembelaan Dato' Rajpal Singh.",
    "publisher": "Harapan Daily",
    "sort": "2024-03-27",
    "dateLabel": "27 Mac 2024",
    "category": "kk-mart",
    "type": "article",
    "thumb": "assets/media/press/harapan-daily-kk-mart-2024.png"
  },
  {
    "id": "scoop-kk-mart-overview",
    "url": "https://www.scoop.my/news/182986/an-overview-of-key-players-embroiled-in-kk-marts-legal-battles-boycotts/",
    "title": "Gambaran pemain utama dalam pertempuran guaman KK Mart",
    "excerpt": "Analisis kontroversi KK Mart yang menyebut peguam jenayah Dato' Rajpal Singh sebagai antara tokoh utama.",
    "publisher": "Scoop",
    "sort": "2024-03-01",
    "dateLabel": "2024",
    "category": "kk-mart",
    "type": "article",
    "thumb": "assets/media/press/scoop-kk-mart-overview.jpg"
  },
  {
    "id": "ktemoc-allah-socks-2024",
    "url": "http://ktemoc.blogspot.com/2024/03/allah-printed-socks-controversy-there.html",
    "title": "Kontroversi stokin bercetak Allah — ulasan guaman",
    "excerpt": "Analisis blog kes stokin KK Mart yang merujuk peguam Dato' Rajpal Singh.",
    "publisher": "Ktemoc",
    "sort": "2024-03-01",
    "dateLabel": "Mac 2024",
    "category": "kk-mart",
    "type": "article",
    "thumb": "assets/media/press/ktemoc-allah-socks-2024.png"
  },
  {
    "id": "nst-kk-mart-justice-2024",
    "url": "https://www.nst.com.my/news/crime-courts/2024/03/1030912/kk-mart-lawyers-let-justice-take-its-course-nsttv",
    "title": "Peguam KK Mart: Biarkan keadilan berjalan",
    "excerpt": "Peguam Dato' Rajpal Singh menasihatkan orang awam supaya tidak membuat komen yang boleh menjejaskan perbicaraan adil.",
    "publisher": "New Straits Times",
    "sort": "2024-03-26",
    "dateLabel": "26 Mac 2024",
    "category": "kk-mart",
    "type": "article",
    "featured": true,
    "thumb": "assets/media/press/nst-kk-mart.jpg"
  },
  {
    "id": "edge-kk-mart-charges-2024",
    "url": "https://theedgemalaysia.com/node/705937",
    "title": "Pengasas KK Mart, isteri dan pembekal didakwa; mohon tidak bersalah",
    "excerpt": "Dato' Rajpal Singh mewakili pengasas KK Mart Datuk Seri Dr Chai Kee Kan di Mahkamah Sesyen Shah Alam.",
    "publisher": "The Edge Malaysia",
    "sort": "2024-03-26",
    "dateLabel": "26 Mac 2024",
    "category": "kk-mart",
    "type": "article",
    "featured": true,
    "thumb": "assets/media/press/edge-kk-mart.jpg"
  },
  {
    "id": "youtube-star-kk-mart-2024",
    "url": "https://www.youtube.com/watch?v=9lAQSmj59_k",
    "title": "Biarkan keadilan berjalan, kata peguam mewakili KK Mart",
    "excerpt": "Dato' Rajpal Singh dan Datuk David Gurupatham berbicara kepada media di luar kompleks mahkamah Shah Alam.",
    "publisher": "The Star (YouTube)",
    "sort": "2024-03-26",
    "dateLabel": "26 Mac 2024",
    "category": "kk-mart",
    "type": "video",
    "featured": true,
    "youtubeId": "9lAQSmj59_k"
  },
  {
    "id": "youtube-utusan-kk-chai-2024",
    "url": "https://www.youtube.com/watch?v=Jw1B5p4WGxA",
    "title": "Sidang media peguam mewakili Datuk Seri Dr KK Chai",
    "excerpt": "Sidang media isu stokin Allah KK Mart memaparkan peguam Dato' Rajpal Singh.",
    "publisher": "Utusan Malaysia (YouTube)",
    "sort": "2024-03-26",
    "dateLabel": "26 Mac 2024",
    "category": "kk-mart",
    "type": "video",
    "youtubeId": "Jw1B5p4WGxA"
  },
  {
    "id": "youtube-kk-mart-0VKhcAhZzIs",
    "url": "https://www.youtube.com/watch?v=0VKhcAhZzIs",
    "title": "Kes Maniishapriet, geng Punjabi, dan bunuhan terinspirasi filem",
    "excerpt": "Podcast The Brand Room: Dato' Rajpal Singh membincangkan kes bunuh pelajar Cyberjaya, perbicaraan berprofil tinggi, dan undang-undang jenayah di Malaysia.",
    "publisher": "The Brand Room",
    "sort": "2026-05-02",
    "dateLabel": "2 Mei 2026",
    "category": "criminal-trials",
    "type": "video",
    "youtubeId": "0VKhcAhZzIs"
  },
  {
    "id": "astro-nicky-gang-2021",
    "url": "https://international.astroawani.com/malaysia-news/14-individuals-linked-nicky-gang-freed-charges-370049",
    "title": "14 individu dikaitkan Geng Nicky dibebaskan daripada pertuduhan",
    "excerpt": "Astro Awani melaporkan kes geng Nicky Liow yang dipertahankan oleh peguam jenayah Dato' Rajpal Singh.",
    "publisher": "Astro Awani",
    "sort": "2021-06-01",
    "dateLabel": "2021",
    "category": "criminal-trials",
    "type": "article",
    "featured": true,
    "thumb": "assets/media/press/astro-nicky-gang-2021.jpg"
  },
  {
    "id": "asiaone-cosplay-killer-2019",
    "url": "https://www.asiaone.com/malaysia/malaysian-man-dubbed-cosplay-killer-gets-22-years-jail-instead-death-upon-appeal",
    "title": "Pembunuh cosplay dijatuhi 22 tahun penjara dan bukannya hukuman mati selepas rayuan",
    "excerpt": "Keputusan Mahkamah Rayuan untuk Poon Wai Hong, diwakili oleh peguam pembelaan jenayah Dato' Rajpal Singh.",
    "publisher": "AsiaOne",
    "sort": "2019-09-12",
    "dateLabel": "12 September 2019",
    "category": "criminal-trials",
    "type": "article",
    "featured": true,
    "thumb": "assets/media/press/asiaone-cosplay-killer-2019.jpg"
  },
  {
    "id": "yahoo-paul-yong-exco",
    "url": "https://malaysia.news.yahoo.com/ex-perak-exco-paul-yong-025421673.html",
    "title": "Bekas exco Perak Paul Yong — prosiding guaman",
    "excerpt": "Liputan Yahoo News kes Paul Yong bersama peguam pembelaan Dato' Rajpal Singh.",
    "publisher": "Yahoo News Malaysia",
    "sort": "2020-01-01",
    "dateLabel": "2020",
    "category": "criminal-trials",
    "type": "article",
    "thumb": "assets/media/press/fallback-yahoo.svg"
  },
  {
    "id": "yahoo-paul-yong-trial-postponed",
    "url": "https://malaysia.news.yahoo.com/rape-trial-postponed-paul-yong-031801403.html",
    "title": "Perbicaraan rogol Paul Yong ditangguh",
    "excerpt": "Laporan penangguhan perbicaraan bekas ahli dewan Perak Paul Yong, dipertahankan oleh Dato' Rajpal Singh.",
    "publisher": "Yahoo News Malaysia",
    "sort": "2020-07-01",
    "dateLabel": "Julai 2020",
    "category": "criminal-trials",
    "type": "article",
    "thumb": "assets/media/press/fallback-yahoo.svg"
  },
  {
    "id": "sabahkini-spanco",
    "url": "https://www.sabahkini2.co/en/news/6066/tan-sri-robert-tan-bos-spanco-didakwa-tipu-mof-rm39-bilion/view",
    "title": "Kes SPanco — Tan Sri Robert Tan didakwa",
    "excerpt": "Liputan pendakwaan penipuan komersial besar melibatkan peguam Dato' Rajpal Singh.",
    "publisher": "Sabahkini",
    "sort": "2018-01-01",
    "dateLabel": "2018",
    "category": "criminal-trials",
    "type": "article",
    "thumb": "assets/media/press/sabahkini-spanco.jpg"
  },
  {
    "id": "bh-rela-compensation-2018",
    "url": "https://www.bharian.com.my/berita/kes/2018/08/461749/anggota-rela-tolak-bayaran-pampasan",
    "title": "Anggota RELA tolak bayaran pampasan",
    "excerpt": "Laporan Berita Harian kes pukul RELA melibatkan Datuk Nicky Liow dan peguam Dato' Rajpal Singh.",
    "publisher": "Berita Harian",
    "sort": "2018-08-15",
    "dateLabel": "15 Ogos 2018",
    "category": "criminal-trials",
    "type": "article",
    "thumb": "assets/media/press/bh-rela-compensation-2018.png"
  },
  {
    "id": "malaymail-najib-lawyers-2018",
    "url": "https://www.malaymail.com/news/malaysia/2018/07/03/after-najibs-arrest-lawyers-say-fine-for-suspects-to-be-held-before-being-c/1648403",
    "title": "Selepas penahanan Najib, peguam ulas peraturan tahanan suspek",
    "excerpt": "Pakar undang-undang jenayah Dato' Rajpal Singh mengulas peraturan tahanan pra-perbicaraan bagi Majlis Peguam Malaysia.",
    "publisher": "Malay Mail",
    "sort": "2018-07-03",
    "dateLabel": "3 Julai 2018",
    "category": "bar-profession",
    "type": "article",
    "featured": true,
    "thumb": "assets/media/press/malaymail-najib-lawyers-2018.jpg"
  },
  {
    "id": "malaymail-igp-twitter-2015",
    "url": "https://www.malaymail.com/news/malaysia/2015/03/19/igps-twitter-policing-leaves-lawyers-conflicted/862241",
    "title": "Polis Twitter IGP mewujudkan kekeliruan dalam kalangan peguam",
    "excerpt": "Pengerusi Jawatankuasa Undang-Undang Jenayah Majlis Peguam Rajpal Singh tentang polis dan etika guaman di Malaysia.",
    "publisher": "Malay Mail",
    "sort": "2015-03-19",
    "dateLabel": "19 Mac 2015",
    "category": "bar-profession",
    "type": "article",
    "thumb": "assets/media/press/malaymail-igp-twitter-2015.jpg"
  },
  {
    "id": "malaysianbar-protect-lawyers",
    "url": "https://www.malaysianbar.org.my/bar_news/berita_badan_peguam/bar_council_to_set_up_special_committee_to_protect_lawyers.html",
    "title": "Majlis Peguam tubuh jawatankuasa khas lindungi peguam",
    "excerpt": "Pengumuman Badan Peguam Malaysia memaparkan peguam advokasi undang-undang jenayah Rajpal Singh.",
    "publisher": "Malaysian Bar",
    "sort": "2010-01-01",
    "dateLabel": "2010",
    "category": "bar-profession",
    "type": "article",
    "thumb": "assets/media/press/fallback-malaysian-bar.svg"
  },
  {
    "id": "malaysianbar-sentencing-guidelines",
    "url": "https://www.malaysianbar.org.my/article/news/legal-and-general-news/legal-news/case-for-sentencing-guidelines",
    "title": "Hujah untuk garis panduan penghukuman",
    "excerpt": "Ulasan guaman oleh pakar undang-undang jenayah Rajpal Singh tentang reformasi penghukuman di Malaysia.",
    "publisher": "Malaysian Bar",
    "sort": "2009-01-01",
    "dateLabel": "2009",
    "category": "bar-profession",
    "type": "article",
    "thumb": "assets/media/press/fallback-malaysian-bar.svg"
  },
  {
    "id": "selangorbar-content-93803",
    "url": "https://www.selangorbar.org/content_dtl.php?id=93803",
    "title": "Badan Peguam Selangor — berita rasmi",
    "excerpt": "Liputan Badan Peguam Selangor melibatkan Dato' Rajpal Singh sebagai peguam jenayah kanan.",
    "publisher": "Selangor Bar",
    "sort": "2010-01-01",
    "dateLabel": "2010",
    "category": "bar-profession",
    "type": "article",
    "thumb": "assets/media/press/fallback-selangor-bar.svg"
  },
  {
    "id": "selangorbar-photo-1839",
    "url": "https://selangorbar.org/photographs_photo.php?album=3&photo=1839",
    "title": "Foto rasmi Badan Peguam Selangor",
    "excerpt": "Foto arkib daripada Badan Peguam Selangor memaparkan peguam Rajpal Singh.",
    "publisher": "Selangor Bar",
    "sort": "2010-01-01",
    "dateLabel": "Arkib",
    "category": "bar-profession",
    "type": "document",
    "thumb": "assets/media/press/fallback-selangor-bar.svg"
  },
  {
    "id": "bar-representative-pdf-2012",
    "url": "https://gizwizstudio.sgp1.cdn.digitaloceanspaces.com/sgorbar-wp20181123/home2/sgorbarg/public_html/_beta/www/2012/02/20-bar-representative.pdf",
    "title": "Dokumen wakil badan peguam (2012)",
    "excerpt": "Dokumen Badan Peguam Selangor menyenaraikan Rajpal Singh sebagai wakil badan peguam.",
    "publisher": "Selangor Bar",
    "sort": "2012-02-20",
    "dateLabel": "20 Februari 2012",
    "category": "bar-profession",
    "type": "document",
    "thumb": "assets/media/press/fallback-document.svg"
  },
  {
    "id": "keehuachee-philanthropist-2020",
    "url": "http://keehuachee.blogspot.com/2020/08/malaysias-youngest-philanthropist-dato.html",
    "title": "Filantropis termuda Malaysia — profil",
    "excerpt": "Profil blog yang menyebut peguam jenayah Dato' Rajpal Singh dalam konteks filantropi komuniti.",
    "publisher": "Kee Huat Chee",
    "sort": "2020-08-01",
    "dateLabel": "Ogos 2020",
    "category": "community",
    "type": "article",
    "thumb": "assets/media/press/keehuachee-philanthropist-2020.jpg"
  },
  {
    "id": "facebook-vasakhi",
    "url": "https://www.facebook.com/100076608946392/videos/on-this-joyous-occasion-of-vasakhi-dato-rajpal-singh-president-of-gurdwara-sahib/1334592824466502/",
    "title": "Mesej Vasakhi — Dato' Rajpal Singh, Gurdwara Sahib",
    "excerpt": "Video Facebook Dato' Rajpal Singh berucap pada sambutan Vasakhi.",
    "publisher": "Facebook",
    "sort": "2024-04-01",
    "dateLabel": "2024",
    "category": "community",
    "type": "social",
    "thumb": "assets/media/press/facebook-vasakhi.jpg"
  },
  {
    "id": "facebook-high-court-kl",
    "url": "https://www.facebook.com/manoharan.malayalam.1/posts/1062026at-the-high-court-criminal-division-at-jalan-dutakuala-lumpur-todaymy-son/36788038037461243/",
    "title": "Di Bahagian Jenayah Mahkamah Tinggi, Kuala Lumpur",
    "excerpt": "Catatan media sosial daripada Bahagian Jenayah Mahkamah Tinggi memaparkan peguam Dato' Rajpal Singh.",
    "publisher": "Facebook",
    "sort": "2024-01-01",
    "dateLabel": "2024",
    "category": "criminal-trials",
    "type": "social",
    "thumb": "assets/media/press/fallback-facebook.svg"
  },
  {
    "id": "tiktok-utusan-kk",
    "url": "https://www.tiktok.com/@utusanonline/video/7350574657910721800",
    "title": "Isu stokin Allah: Sidang media peguam bagi Datuk Seri Dr KK Chai",
    "excerpt": "Klip TikTok Utusan Malaysia peguam Dato' Rajpal Singh pada sidang media kontroversi stokin Allah KK Mart.",
    "publisher": "Utusan Malaysia (TikTok)",
    "sort": "2024-03-26",
    "dateLabel": "26 Mac 2024",
    "category": "kk-mart",
    "type": "social",
    "thumb": "assets/media/press/tiktok-utusan-kk.jpg"
  },
  {
    "id": "tiktok-hmetromy",
    "url": "https://www.tiktok.com/@hmetromy/video/7520509764229532944",
    "title": "Rajpal Singh tentang suspek ditahan dalam kes bunuh anak saudara di Cyberjaya",
    "excerpt": "Klip Harian Metro: Dato' Rajpal Singh berbicara selepas tiga suspek ditahan dalam kes bunuh anak saudaranya Maniishapriet Kaur Akhara.",
    "publisher": "Harian Metro (TikTok)",
    "sort": "2025-06-27",
    "dateLabel": "27 Jun 2025",
    "category": "criminal-trials",
    "type": "social",
    "thumb": "assets/media/press/tiktok-hmetromy.jpg"
  },
  {
    "id": "instagram-reel",
    "url": "https://www.instagram.com/reels/DLW1lq5pSmq/",
    "title": "'Satu nyawa hilang': bapa saudara mangsa persoal tiada CCTV di asrama pelajar",
    "excerpt": "Reel Scoop: Dato' Rajpal Singh, bapa saudara pelajar yang dibunuh, mempersoalkan kekurangan CCTV di penginapan diurus universiti di Cyberjaya.",
    "publisher": "Scoop (Instagram)",
    "sort": "2025-06-26",
    "dateLabel": "26 Jun 2025",
    "category": "criminal-trials",
    "type": "social",
    "thumb": "assets/media/press/fallback-instagram.svg"
  },
  {
    "id": "youtube-XzaT9wGXDmc",
    "url": "https://www.youtube.com/watch?v=XzaT9wGXDmc",
    "title": "Pisahkan jawatan Peguam Negara dan Pendakwa Raya",
    "excerpt": "Temubual KiniTV dengan ahli Majlis Peguam Rajpal Singh mengenai mengapa jawatan Peguam Negara dan Pendakwa Raya tidak sepatutnya dipegang oleh orang yang sama.",
    "publisher": "KiniTV",
    "sort": "2016-06-03",
    "dateLabel": "3 Jun 2016",
    "category": "bar-profession",
    "type": "video",
    "youtubeId": "XzaT9wGXDmc"
  },
  {
    "id": "youtube-KbWK4lspxo4",
    "url": "https://youtu.be/KbWK4lspxo4",
    "title": "Datuk Seri dibebaskan dalam kes pukul RELA",
    "excerpt": "Video The Star: Mahkamah Ampang melepaskan Nicky Liow Soon Hee selepas kompaun RM2,000; Dato' Rajpal Singh mewakili tertuduh.",
    "publisher": "The Star (YouTube)",
    "sort": "2019-05-10",
    "dateLabel": "10 Mei 2019",
    "category": "criminal-trials",
    "type": "video",
    "youtubeId": "KbWK4lspxo4"
  },
  {
    "id": "youtube-rajpal-bhTq-L5jtf8",
    "url": "https://www.youtube.com/watch?v=bhTq-L5jtf8",
    "title": "Peguam KK Mart: Biarkan keadilan berjalan",
    "excerpt": "Video NST Online: Dato' Rajpal Singh menasihatkan orang awam supaya tidak membuat komen prasangka selepas pengasas KK Mart didakwa berkaitan stokin Allah.",
    "publisher": "NST Online (YouTube)",
    "sort": "2024-03-26",
    "dateLabel": "26 Mac 2024",
    "category": "kk-mart",
    "type": "video",
    "youtubeId": "bhTq-L5jtf8"
  }
];

