/**
 * Press coverage library — external articles, video, and social mentions.
 */

/** @typedef {'article' | 'video' | 'social' | 'document'} PressType */

/**
 * @typedef {Object} PressItem
 * @property {string} id
 * @property {string} url
 * @property {string} title
 * @property {string} excerpt
 * @property {string} publisher
 * @property {string} sort ISO date for ordering
 * @property {string} dateLabel
 * @property {string} category
 * @property {PressType} type
 * @property {boolean} [featured]
 * @property {string} [thumb] Path from site root, e.g. assets/media/press/foo.jpg
 * @property {string} [youtubeId]
 */

/** @type {{ id: string, label: string }[]} */
export const PRESS_CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'criminal-trials', label: 'Criminal trials' },
  { id: 'kk-mart', label: 'KK Mart' },
  { id: 'bar-profession', label: 'Bar & profession' },
  { id: 'video-social', label: 'Video & social' },
  { id: 'community', label: 'Community' },
];

/** @type {PressItem[]} */
export const PRESS_ITEMS = [
  {
    id: 'star-organised-crime-2026',
    url: 'https://www.thestar.com.my/news/nation/2026/05/25/11-men-charged-with-being-members-of-organised-crime-group',
    title: '11 men charged with being members of organised crime group',
    excerpt: 'Coverage of organised crime charges featuring criminal defence lawyer Dato\' Rajpal Singh in Malaysia.',
    publisher: 'The Star',
    sort: '2026-05-25',
    dateLabel: '25 May 2026',
    category: 'criminal-trials',
    type: 'article',
    thumb: 'assets/media/press/star-organised-crime-2026.jpg',
  },
  {
    id: 'malaysia-gazette-harmoni-2025',
    url: 'https://malaysiagazette.com/2025/04/12/hidup-harmoni-perpaduan-penting-rajpal/',
    title: 'Hidup harmoni, perpaduan penting — Dato\' Rajpal Singh',
    excerpt: 'Dato\' Rajpal Singh speaks on harmony and unity in Malaysian community life.',
    publisher: 'Malaysia Gazette',
    sort: '2025-04-12',
    dateLabel: '12 April 2025',
    category: 'community',
    type: 'article',
    featured: true,
    thumb: 'assets/media/press/malaysia-gazette-harmoni-2025.jpg',
  },
  {
    id: 'star-paul-yong-appeal-2024',
    url: 'https://www.thestar.com.my/news/nation/2024/09/05/apex-court-to-hear-paul-yong039s-rape-conviction-appeal-on-oct-23',
    title: 'Apex court to hear Paul Yong\'s rape conviction appeal',
    excerpt: 'Federal Court appeal coverage involving former Perak assemblyman Paul Yong and counsel Dato\' Rajpal Singh.',
    publisher: 'The Star',
    sort: '2024-09-05',
    dateLabel: '5 September 2024',
    category: 'criminal-trials',
    type: 'article',
    featured: true,
    thumb: 'assets/media/press/star-paul-yong-appeal-2024.jpg',
  },
  {
    id: 'bh-kk-mart-family-2024',
    url: 'https://www.bharian.com.my/berita/nasional/2024/07/1271686/124-hari-penuh-sengsara-dalam-hidup-saya-keluarga-pengasas-kk-mart',
    title: '124 hari penuh sengsara — Pengasas KK Mart',
    excerpt: 'Berita Harian report on the KK Mart founder\'s family following the Allah socks controversy, with Dato\' Rajpal Singh as counsel.',
    publisher: 'Berita Harian',
    sort: '2024-07-15',
    dateLabel: '15 July 2024',
    category: 'kk-mart',
    type: 'article',
    thumb: 'assets/media/press/bh-kk-mart.jpg',
  },
  {
    id: 'utusan-kk-mart-verdict-2024',
    url: 'https://www.utusan.com.my/nasional/2024/07/keputusan-mahkamah-diharap-tamatkan-isu-kk-mart/',
    title: 'Keputusan mahkamah diharap tamatkan isu KK Mart',
    excerpt: 'Dato\' Rajpal Singh said the court had decided and the public should not prolong the KK Mart matter.',
    publisher: 'Utusan Malaysia',
    sort: '2024-07-15',
    dateLabel: '15 July 2024',
    category: 'kk-mart',
    type: 'article',
    thumb: 'assets/media/press/utusan-kk-mart.jpg',
  },
  {
    id: 'harapan-daily-kk-mart-2024',
    url: 'https://harapandaily.com/2024/03/27/justice-will-prevail-for-kk-mart/',
    title: 'Justice will prevail for KK Mart',
    excerpt: 'Press report on the KK Mart Allah socks case featuring defence lawyer Dato\' Rajpal Singh.',
    publisher: 'Harapan Daily',
    sort: '2024-03-27',
    dateLabel: '27 March 2024',
    category: 'kk-mart',
    type: 'article',
    thumb: 'assets/media/press/harapan-daily-kk-mart-2024.png',
  },
  {
    id: 'scoop-kk-mart-overview',
    url: 'https://www.scoop.my/news/182986/an-overview-of-key-players-embroiled-in-kk-marts-legal-battles-boycotts/',
    title: 'Overview of key players in KK Mart\'s legal battles',
    excerpt: 'Analysis of the KK Mart controversy naming criminal lawyer Dato\' Rajpal Singh among central figures.',
    publisher: 'Scoop',
    sort: '2024-03-01',
    dateLabel: '2024',
    category: 'kk-mart',
    type: 'article',
    thumb: 'assets/media/press/scoop-kk-mart-overview.jpg',
  },
  {
    id: 'ktemoc-allah-socks-2024',
    url: 'http://ktemoc.blogspot.com/2024/03/allah-printed-socks-controversy-there.html',
    title: 'Allah printed socks controversy — legal commentary',
    excerpt: 'Blog analysis of the KK Mart socks case referencing counsel Dato\' Rajpal Singh.',
    publisher: 'Ktemoc',
    sort: '2024-03-01',
    dateLabel: 'March 2024',
    category: 'kk-mart',
    type: 'article',
    thumb: 'assets/media/press/ktemoc-allah-socks-2024.png',
  },
  {
    id: 'nst-kk-mart-justice-2024',
    url: 'https://www.nst.com.my/news/crime-courts/2024/03/1030912/kk-mart-lawyers-let-justice-take-its-course-nsttv',
    title: 'KK Mart lawyers: Let justice take its course',
    excerpt: 'Counsel Dato\' Rajpal Singh urged the public to refrain from comments that could prejudice a fair trial.',
    publisher: 'New Straits Times',
    sort: '2024-03-26',
    dateLabel: '26 March 2024',
    category: 'kk-mart',
    type: 'article',
    featured: true,
    thumb: 'assets/media/press/nst-kk-mart.jpg',
  },
  {
    id: 'edge-kk-mart-charges-2024',
    url: 'https://theedgemalaysia.com/node/705937',
    title: 'KK Mart founder, wife and supplier charged; plead not guilty',
    excerpt: 'Dato\' Rajpal Singh represented KK Mart founder Datuk Seri Dr Chai Kee Kan at the Shah Alam Sessions Court.',
    publisher: 'The Edge Malaysia',
    sort: '2024-03-26',
    dateLabel: '26 March 2024',
    category: 'kk-mart',
    type: 'article',
    featured: true,
    thumb: 'assets/media/press/edge-kk-mart.jpg',
  },
  {
    id: 'youtube-star-kk-mart-2024',
    url: 'https://www.youtube.com/watch?v=9lAQSmj59_k',
    title: 'Allow justice to take its course, say lawyers representing KK Mart',
    excerpt: 'Dato\' Rajpal Singh and Datuk David Gurupatham speak to media outside the Shah Alam court complex.',
    publisher: 'The Star (YouTube)',
    sort: '2024-03-26',
    dateLabel: '26 March 2024',
    category: 'kk-mart',
    type: 'video',
    featured: true,
    youtubeId: '9lAQSmj59_k',
  },
  {
    id: 'youtube-utusan-kk-chai-2024',
    url: 'https://www.youtube.com/watch?v=Jw1B5p4WGxA',
    title: 'Sidang media peguam mewakili Datuk Seri Dr KK Chai',
    excerpt: 'Press conference on the KK Mart Allah socks issue featuring counsel Dato\' Rajpal Singh.',
    publisher: 'Utusan Malaysia (YouTube)',
    sort: '2024-03-26',
    dateLabel: '26 March 2024',
    category: 'kk-mart',
    type: 'video',
    youtubeId: 'Jw1B5p4WGxA',
  },
  {
    id: 'youtube-kk-mart-0VKhcAhZzIs',
    url: 'https://www.youtube.com/watch?v=0VKhcAhZzIs',
    title: 'Maniishapriet\'s case, Punjabi gangs, and movie-inspired murders',
    excerpt: 'The Brand Room podcast: Dato\' Rajpal Singh discusses the Cyberjaya student murder, high-profile trials, and criminal law in Malaysia.',
    publisher: 'The Brand Room',
    sort: '2026-05-02',
    dateLabel: '2 May 2026',
    category: 'criminal-trials',
    type: 'video',
    youtubeId: '0VKhcAhZzIs',
  },
  {
    id: 'astro-nicky-gang-2021',
    url: 'https://international.astroawani.com/malaysia-news/14-individuals-linked-nicky-gang-freed-charges-370049',
    title: '14 individuals linked to Nicky Gang freed of charges',
    excerpt: 'Astro Awani reports on the Nicky Liow gang case defended by criminal lawyer Dato\' Rajpal Singh.',
    publisher: 'Astro Awani',
    sort: '2021-06-01',
    dateLabel: '2021',
    category: 'criminal-trials',
    type: 'article',
    featured: true,
    thumb: 'assets/media/press/astro-nicky-gang-2021.jpg',
  },
  {
    id: 'asiaone-cosplay-killer-2019',
    url: 'https://www.asiaone.com/malaysia/malaysian-man-dubbed-cosplay-killer-gets-22-years-jail-instead-death-upon-appeal',
    title: 'Cosplay killer gets 22 years\' jail instead of death upon appeal',
    excerpt: 'Court of Appeal decision for Poon Wai Hong, represented by criminal defence lawyer Dato\' Rajpal Singh.',
    publisher: 'AsiaOne',
    sort: '2019-09-12',
    dateLabel: '12 September 2019',
    category: 'criminal-trials',
    type: 'article',
    featured: true,
    thumb: 'assets/media/press/asiaone-cosplay-killer-2019.jpg',
  },
  {
    id: 'yahoo-paul-yong-exco',
    url: 'https://malaysia.news.yahoo.com/ex-perak-exco-paul-yong-025421673.html',
    title: 'Ex-Perak exco Paul Yong — legal proceedings',
    excerpt: 'Yahoo News coverage of the Paul Yong case with defence counsel Dato\' Rajpal Singh.',
    publisher: 'Yahoo News Malaysia',
    sort: '2020-01-01',
    dateLabel: '2020',
    category: 'criminal-trials',
    type: 'article',
    thumb: 'assets/media/press/fallback-yahoo.svg',
  },
  {
    id: 'yahoo-paul-yong-trial-postponed',
    url: 'https://malaysia.news.yahoo.com/rape-trial-postponed-paul-yong-031801403.html',
    title: 'Rape trial postponed for Paul Yong',
    excerpt: 'Report on the adjournment of former Perak assemblyman Paul Yong\'s trial, defended by Dato\' Rajpal Singh.',
    publisher: 'Yahoo News Malaysia',
    sort: '2020-07-01',
    dateLabel: 'July 2020',
    category: 'criminal-trials',
    type: 'article',
    thumb: 'assets/media/press/fallback-yahoo.svg',
  },
  {
    id: 'sabahkini-spanco',
    url: 'https://www.sabahkini2.co/en/news/6066/tan-sri-robert-tan-bos-spanco-didakwa-tipu-mof-rm39-bilion/view',
    title: 'SPanco case — Tan Sri Robert Tan charged',
    excerpt: 'Coverage of a major commercial fraud prosecution involving counsel Dato\' Rajpal Singh.',
    publisher: 'Sabahkini',
    sort: '2018-01-01',
    dateLabel: '2018',
    category: 'criminal-trials',
    type: 'article',
    thumb: 'assets/media/press/sabahkini-spanco.jpg',
  },
  {
    id: 'bh-rela-compensation-2018',
    url: 'https://www.bharian.com.my/berita/kes/2018/08/461749/anggota-rela-tolak-bayaran-pampasan',
    title: 'Anggota RELA tolak bayaran pampasan',
    excerpt: 'Berita Harian report on the RELA assault case involving Datuk Nicky Liow and lawyer Dato\' Rajpal Singh.',
    publisher: 'Berita Harian',
    sort: '2018-08-15',
    dateLabel: '15 August 2018',
    category: 'criminal-trials',
    type: 'article',
    thumb: 'assets/media/press/bh-rela-compensation-2018.png',
  },
  {
    id: 'malaymail-najib-lawyers-2018',
    url: 'https://www.malaymail.com/news/malaysia/2018/07/03/after-najibs-arrest-lawyers-say-fine-for-suspects-to-be-held-before-being-c/1648403',
    title: 'After Najib\'s arrest, lawyers comment on holding suspects',
    excerpt: 'Criminal law expert Dato\' Rajpal Singh comments on pre-trial detention rules for Malaysian Bar.',
    publisher: 'Malay Mail',
    sort: '2018-07-03',
    dateLabel: '3 July 2018',
    category: 'bar-profession',
    type: 'article',
    featured: true,
    thumb: 'assets/media/press/malaymail-najib-lawyers-2018.jpg',
  },
  {
    id: 'malaymail-igp-twitter-2015',
    url: 'https://www.malaymail.com/news/malaysia/2015/03/19/igps-twitter-policing-leaves-lawyers-conflicted/862241',
    title: 'IGP\'s Twitter policing leaves lawyers conflicted',
    excerpt: 'Bar Council Criminal Law Committee chairman Rajpal Singh on policing and legal ethics in Malaysia.',
    publisher: 'Malay Mail',
    sort: '2015-03-19',
    dateLabel: '19 March 2015',
    category: 'bar-profession',
    type: 'article',
    thumb: 'assets/media/press/malaymail-igp-twitter-2015.jpg',
  },
  {
    id: 'malaysianbar-protect-lawyers',
    url: 'https://www.malaysianbar.org.my/bar_news/berita_badan_peguam/bar_council_to_set_up_special_committee_to_protect_lawyers.html',
    title: 'Bar Council to set up committee to protect lawyers',
    excerpt: 'Malaysian Bar announcement featuring criminal law advocate Rajpal Singh.',
    publisher: 'Malaysian Bar',
    sort: '2010-01-01',
    dateLabel: '2010',
    category: 'bar-profession',
    type: 'article',
    thumb: 'assets/media/press/fallback-malaysian-bar.svg',
  },
  {
    id: 'malaysianbar-sentencing-guidelines',
    url: 'https://www.malaysianbar.org.my/article/news/legal-and-general-news/legal-news/case-for-sentencing-guidelines',
    title: 'The case for sentencing guidelines',
    excerpt: 'Legal commentary by criminal law expert Rajpal Singh on Malaysian sentencing reform.',
    publisher: 'Malaysian Bar',
    sort: '2009-01-01',
    dateLabel: '2009',
    category: 'bar-profession',
    type: 'article',
    thumb: 'assets/media/press/fallback-malaysian-bar.svg',
  },
  {
    id: 'selangorbar-content-93803',
    url: 'https://www.selangorbar.org/content_dtl.php?id=93803',
    title: 'Selangor Bar — official news',
    excerpt: 'Selangor Bar coverage involving Dato\' Rajpal Singh in his capacity as a senior criminal lawyer.',
    publisher: 'Selangor Bar',
    sort: '2010-01-01',
    dateLabel: '2010',
    category: 'bar-profession',
    type: 'article',
    thumb: 'assets/media/press/fallback-selangor-bar.svg',
  },
  {
    id: 'selangorbar-photo-1839',
    url: 'https://selangorbar.org/photographs_photo.php?album=3&photo=1839',
    title: 'Selangor Bar official photograph',
    excerpt: 'Archive photograph from the Selangor Bar featuring lawyer Rajpal Singh.',
    publisher: 'Selangor Bar',
    sort: '2010-01-01',
    dateLabel: 'Archive',
    category: 'bar-profession',
    type: 'document',
    thumb: 'assets/media/press/fallback-selangor-bar.svg',
  },
  {
    id: 'bar-representative-pdf-2012',
    url: 'https://gizwizstudio.sgp1.cdn.digitaloceanspaces.com/sgorbar-wp20181123/home2/sgorbarg/public_html/_beta/www/2012/02/20-bar-representative.pdf',
    title: 'Bar representative document (2012)',
    excerpt: 'Selangor Bar document listing Rajpal Singh as bar representative.',
    publisher: 'Selangor Bar',
    sort: '2012-02-20',
    dateLabel: '20 February 2012',
    category: 'bar-profession',
    type: 'document',
    thumb: 'assets/media/press/fallback-document.svg',
  },
  {
    id: 'keehuachee-philanthropist-2020',
    url: 'http://keehuachee.blogspot.com/2020/08/malaysias-youngest-philanthropist-dato.html',
    title: 'Malaysia\'s youngest philanthropist — profile',
    excerpt: 'Blog profile mentioning criminal lawyer Dato\' Rajpal Singh in a community philanthropy context.',
    publisher: 'Kee Huat Chee',
    sort: '2020-08-01',
    dateLabel: 'August 2020',
    category: 'community',
    type: 'article',
    thumb: 'assets/media/press/keehuachee-philanthropist-2020.jpg',
  },
  {
    id: 'facebook-vasakhi',
    url: 'https://www.facebook.com/100076608946392/videos/on-this-joyous-occasion-of-vasakhi-dato-rajpal-singh-president-of-gurdwara-sahib/1334592824466502/',
    title: 'Vasakhi message — Dato\' Rajpal Singh, Gurdwara Sahib',
    excerpt: 'Facebook video of Dato\' Rajpal Singh speaking on the occasion of Vasakhi.',
    publisher: 'Facebook',
    sort: '2024-04-01',
    dateLabel: '2024',
    category: 'community',
    type: 'social',
    thumb: 'assets/media/press/facebook-vasakhi.jpg',
  },
  {
    id: 'facebook-high-court-kl',
    url: 'https://www.facebook.com/manoharan.malayalam.1/posts/1062026at-the-high-court-criminal-division-at-jalan-dutakuala-lumpur-todaymy-son/36788038037461243/',
    title: 'At the High Court Criminal Division, Kuala Lumpur',
    excerpt: 'Social post from the High Court criminal division featuring lawyer Dato\' Rajpal Singh.',
    publisher: 'Facebook',
    sort: '2024-01-01',
    dateLabel: '2024',
    category: 'criminal-trials',
    type: 'social',
    thumb: 'assets/media/press/fallback-facebook.svg',
  },
  {
    id: 'tiktok-utusan-kk',
    url: 'https://www.tiktok.com/@utusanonline/video/7350574657910721800',
    title: 'Allah socks issue: Press conference by lawyers for Datuk Seri Dr KK Chai',
    excerpt: 'Utusan Malaysia TikTok clip of counsel Dato\' Rajpal Singh at a press conference on the KK Mart Allah socks controversy.',
    publisher: 'Utusan Malaysia (TikTok)',
    sort: '2024-03-26',
    dateLabel: '26 March 2024',
    category: 'kk-mart',
    type: 'social',
    thumb: 'assets/media/press/tiktok-utusan-kk.jpg',
  },
  {
    id: 'tiktok-hmetromy',
    url: 'https://www.tiktok.com/@hmetromy/video/7520509764229532944',
    title: 'Rajpal Singh on suspects held in niece\'s Cyberjaya murder case',
    excerpt: 'Harian Metro clip: Dato\' Rajpal Singh speaks after three suspects were detained in the murder of his niece Maniishapriet Kaur Akhara.',
    publisher: 'Harian Metro (TikTok)',
    sort: '2025-06-27',
    dateLabel: '27 June 2025',
    category: 'criminal-trials',
    type: 'social',
    thumb: 'assets/media/press/tiktok-hmetromy.jpg',
  },
  {
    id: 'instagram-reel',
    url: 'https://www.instagram.com/reels/DLW1lq5pSmq/',
    title: '\'Now a life is lost\': victim\'s uncle on missing CCTV at student housing',
    excerpt: 'Scoop reel: Dato\' Rajpal Singh, uncle of murdered student Maniishapriet Kaur, questions the lack of CCTV at university-managed accommodation in Cyberjaya.',
    publisher: 'Scoop (Instagram)',
    sort: '2025-06-26',
    dateLabel: '26 June 2025',
    category: 'criminal-trials',
    type: 'social',
    thumb: 'assets/media/press/fallback-instagram.svg',
  },
  {
    id: 'youtube-XzaT9wGXDmc',
    url: 'https://www.youtube.com/watch?v=XzaT9wGXDmc',
    title: 'Separate attorney general, public prosecutor positions',
    excerpt: 'KiniTV interview with Bar Council member Rajpal Singh on why the AG and public prosecutor roles should not be held by the same person.',
    publisher: 'KiniTV',
    sort: '2016-06-03',
    dateLabel: '3 June 2016',
    category: 'bar-profession',
    type: 'video',
    youtubeId: 'XzaT9wGXDmc',
  },
  {
    id: 'youtube-KbWK4lspxo4',
    url: 'https://youtu.be/KbWK4lspxo4',
    title: 'Datuk Seri in Rela assault case acquitted',
    excerpt: 'The Star video: Ampang court discharges Nicky Liow Soon Hee after RM2,000 compound; Dato\' Rajpal Singh represented the accused.',
    publisher: 'The Star (YouTube)',
    sort: '2019-05-10',
    dateLabel: '10 May 2019',
    category: 'criminal-trials',
    type: 'video',
    youtubeId: 'KbWK4lspxo4',
  },
  {
    id: 'youtube-rajpal-bhTq-L5jtf8',
    url: 'https://www.youtube.com/watch?v=bhTq-L5jtf8',
    title: 'KK Mart lawyers: Let justice take its course',
    excerpt: 'NST Online video: Dato\' Rajpal Singh urges the public to refrain from prejudicial comments after KK Mart founders were charged over Allah socks.',
    publisher: 'NST Online (YouTube)',
    sort: '2024-03-26',
    dateLabel: '26 March 2024',
    category: 'kk-mart',
    type: 'video',
    youtubeId: 'bhTq-L5jtf8',
  },
];
